version: "3.7"
services:
  node:
    build: .
    user: "node"
    depends_on:
      - mysql-db
    volumes:
      - ./:/app
    ports:
      - "80"
    environment:
      NODE_ENV: development

  mysql-db:
    env_file:
      - ".env"
    image: "mariadb:10.5.8"
    command:
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "3306"
    restart: unless-stopped