name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just a placeholder, real known_hosts is generated below'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Output working directory
        run: ls -lah

      - name: Deploy with rsync
        run: rsync -rlDvzP ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:repos/eatba/food-order-backend
